### ISSUE TITLE
[13pt] Prioritize Local Processing

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/RRASSLER#2]
Gulp.. I forget what this meant but you said you will remember. Was this the processing all models through RRASSLER to local first, then a separate step to iterate and push to S3?

**Comment by JamesColl-NOAA** [comment]
I did :)
A preliminary timing did show that the disk path was more efficient given how I was using it but this should only be used as a guide.  All functions still remain for further testing.
![image](https://github.com/user-attachments/assets/e57d79a0-78ae-4a41-9868-36c113ef1c64)
