### ISSUE TITLE
[3pt] Add source code to models_catalog.csv

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/RRASSLER#7]
Add a new column to the models_catalog.csv when it is created for "source_code". The only value we have at this point is "ble".

**Comment by JamesColl-NOAA** [comment]
Added in the recent iterations, we now track the following:
```{r}
> OWP_models <- data.table::fread(".../OWP_ras_models_catalog.csv")
> unique(OWP_models$source_code)
[1] "rfc" "ble" "ifc"
```
