### ISSUE TITLE
Dependency error with installation of `NOAA-OWP/RRASSLER` package

### ISSUE THREAD

**Issue by ar-siddiqui** [NOAA-OWP/RRASSLER#8]
Using the provided Dockerfile for setup and then following the steps laid out in `README.rmd`:
`remotes::install_github("NOAA-OWP/RRASSLER")` errors out with 
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘rgdal’
```

**Comment by JamesColl-NOAA** [comment]
This dependency has been removed in the most recent version of the package, and given that the code has now been packaged, we've removed the development environment notes and associated dockerfile as that seemed to have caused more confusion than the reproducibility added.  Thanks for testing this for us and please open a new issue if `remotes::install_github("NOAA-OWP/RRASSLER")` fails for you.
