### ISSUE TITLE
Confusing Dockerfile instructions

### ISSUE THREAD

**Issue by ar-siddiqui** [NOAA-OWP/RRASSLER#9]
The initial two lines of the Dockerfile instruct to build the Docker image in the context of `/path/to/rocker-versioned2`

The `geodev.Dockerfile` does not seem to be using the context. The Dockerfile primarily involves package installations and script executions, with no direct references to files in the context.

I successfully build the docker image without the context, hence not sure if the context is necessary here.

**Comment by JamesColl-NOAA** [comment]
we've removed the development environment notes and associated dockerfile as that seemed to have caused more confusion than the reproducibility added. Thanks for testing this for us and please open a new issue if `remotes::install_github("NOAA-OWP/RRASSLER")` fails for you.
